### ISSUE TITLE
请问里面的参数怎么获取？

### ISSUE THREAD

**Issue by nyano** [mxyooR/Kuro-autosignin#1]
"name" : "",
            "roleId": "",
            "tokenraw": "",
            "userId": "",
            "devCode":""

token已获得
name值看起来好像是可以自定义的
roleld、devcode不知道哪里
userid是游戏内UID么

**Comment by nyano** [comment]
userid应该是账户UID ，roleld看起来是鸣潮UID
devcode不知道是什么，ios么

**Comment by nyano** [comment]
成功了大佬，虽然不知道devcode是什么
【1】增加编码指定
    with open('data.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
【2】删掉了schedule.every().day.at("09:00").do(sign_in) 定时
【3】似乎只支持单设备登陆，登录后，自己设备端会被顶掉，按这个逻辑似乎没法扔青龙，除非设备端别登。这破软件限死了只能手机登录好烦啊

**Comment by mxyooR** [comment]
是只支持单设备登陆，可以抓登陆包，我tools提供的方案是模拟登录

**Comment by mxyooR** [comment]
抓登陆包把token提取出来就行，或者你打开库街区他请求头里面也有
