### ISSUE TITLE
main.py 中 checkpush 错误

### ISSUE THREAD

**Issue by dentylife** [mxyooR/Kuro-autosignin#11]
根据 data.json 结构 
main.py 中第 38 行: checkpush = user['push'] 应是 checkpush = data['push'], 并且放到循环外
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/fbeef7d6-dc06-4fa3-9a95-462418295f41">

**Comment by mxyooR** [comment]
感谢反馈 已修复
