### ISSUE TITLE
token的有效期一般为多久

### ISSUE THREAD

**Issue by 1634222787** [mxyooR/Kuro-autosignin#13]
首先感谢大佬的贡献，我已经在云函数上成功的部署了这个项目
想问一下通过抓包获取的库街区token有效期一般为多久？
库街区一个设备同时只能登录一个账户，我目前有多用户的需求，所以想问一下

**Comment by mxyooR** [comment]
多用户的话可以用tools里面的发验证码获取token

**Comment by mxyooR** [comment]
按道理有效期一直到下一次在别的设备上登录，该token失效，但是可能有的时候有风控

**Comment by mxyooR** [comment]
或者抓包的话在同一设备上用户a登陆了抓了退了，然后登录用户b的抓包，用户a、b的token都能正常用

**Comment by 1634222787** [comment]
ok，感谢
我了解的是即使在设备上登录了如果长时间不使用库街区的话，那么下一次进去的时候可能会掉登录。所以想问一下这个token的问题有获取工具的话就挺方便的
