### ISSUE TITLE
你好，出现这种问题是什么原因，百度解决不了

### ISSUE THREAD

**Issue by happyvv0v0** [mxyooR/Kuro-autosignin#15]
![1](https://github.com/user-attachments/assets/625b657b-0f1a-45e7-8c6c-dcee5caead8b)

**Comment by mxyooR** [comment]
网络问题 挂代理或者过段时间再拉

**Comment by happyvv0v0** [comment]
重新搭建青龙面板后就可以了，谢谢

**Comment by happyvv0v0** [comment]
[
![2](https://github.com/user-attachments/assets/46339284-624a-4325-a08c-a0d2443d29db)
](url)
拉取库之后，没有config文件夹，我手动添加了，等明天看看能不能签到

**Comment by happyvv0v0** [comment]
![3](https://github.com/user-attachments/assets/e6b3be2d-84f4-4387-a12c-a64e1e5cc200)
手动执行了，牛逼
