### ISSUE TITLE
eeeroleId留空报错

### ISSUE THREAD

**Issue by chuyinluotian01** [mxyooR/Kuro-autosignin#7]
![image](https://github.com/user-attachments/assets/db6331c7-86bb-4c3b-9ef4-d3736de0aa66)

**Comment by chuyinluotian01** [comment]
![image](https://github.com/user-attachments/assets/c41378b3-6d92-4865-9d19-c8f3551f092b)
因为没有战双的号，所以暂时把脚本中战双的签到注销了，不过库洛你是不是也开始搞事了，居然开始出信息异常了

**Comment by mxyooR** [comment]
把json中的eeeroldId改成eeeroleId 拼错了

**Comment by chuyinluotian01** [comment]
> 把json中的eeeroldId改成eeeroleId 拼错了

还真是 你不说我都没发现 mainpy确实是 #eeeroleId = user['eeeroleId']  真的眼瞎了
但凡我仔细一点也能发现

**Comment by mxyooR** [comment]
我的问题拼错了😢
