### ISSUE TITLE
报错：战双签到失败

### ISSUE THREAD

**Issue by TLOCN** [mxyooR/Kuro-autosignin#8]
![image](https://github.com/user-attachments/assets/0ac0042d-205d-4539-83ff-46c9d03fda5a)

![image](https://github.com/user-attachments/assets/6a950134-224c-49dd-986c-84a3ca3aea3c)
这里有个2没删，会导致战双签到及日常失败，同时感谢作者添加战双签到（狗头）

**Comment by TLOCN** [comment]
game_check_in.py下的

**Comment by TLOCN** [comment]
删除后青龙面板不再报错
![image](https://github.com/user-attachments/assets/b89fdc27-a49a-49a6-a23d-748e67a58082)

**Comment by mxyooR** [comment]
好的好的

**Comment by mxyooR** [comment]
没战双的号所以没测试就发了
